# Studi Kasus FIFA Dataset

1. Import data FIFA atau FIFA_completed (data lebih kompleks), bisa di pilih salah satunya.
2. Lakukan langkah awal Exploratory Data Analysis dengan melihat summary statistics yang ada pada dataframe. # Gunakan method info dan describe
3. Perlihatkan 10 data pertama menggunakan method head
4. Perlihatkan 10 data terakhir menggunakan method tail
5. Pilih 10 column yang menurut anda paling relevan (dengan teknik subsetting [[ ]]) dan buat variabel baru
6. Dari column yang sudah di pilih analisa beberapa columns, siapa yang mempunyai nilai tertinggi (e.g: rating/salary/passing/dribbling/etc.)
7. Analisa juga siapa yang mempunyai nilai terendah dari beberapa columns tersebut
8. Analisa pada setiap columns nilai rata-rata dan nilai tengah
9. Cari data pemain yang ingin anda pilih dan perlihatkan keseluruhan data dengan teknik subsetting .iloc / .loc
10. Tampilkan plot sederhana yang sudah tersedia pada pandas library. Gunakan .plot() pada column yang disubset (e.g: fifa_data["rating"].plot() dan terapkan pada beberapa column yang telah dipilih

In [2]:
# FIFA Dataset
import pandas as pd
fifa_dataset = pd.read_csv("../../data/input/FIFA_dirty_dataset.csv", index_col = 0).head(6)
fifa_dataset

,name,rating,position,height,foot,rare,pace,shooting,passing,dribbling,defending,heading,diving,handling,kicking,reflexes,speed,positioning
id,,,,,,,,,,,,,,,,,,
1001,G치bor Kir치ly,69,GK,191,Right,0,,,,,,,70,66,63,74,35,66.0
100143,Frederik Boi,65,M,184,Right,0,61,65,63,59,62,62,,,,,,NaN
100264,Tomasz Szewczuk,57,A,185,Right,0,65,54,43,53,55,74,,,,,,NaN
100325,Steeve Joseph-Reinette,63,D,180,Left,0,68,38,51,46,64,71,,,,,,NaN
100326,Kamel Chafni,72,M,181,Right,0,75,64,67,72,57,66,,,,,,NaN
100329,Abdoulaye Faye,72,D,187,Right,1,50,37,47,43,76,82,,,,,,NaN

In [15]:
fifa_dataset_tail = pd.read_csv("../../data/input/FIFA_dirty_dataset.csv", index_col = 0).tail(10)
fifa_dataset_tail

,name,rating,position,height,foot,rare,pace,shooting,passing,dribbling,defending,heading,diving,handling,kicking,reflexes,speed,positioning
id,,,,,,,,,,,,,,,,,,
9722,Nicolai Stokholm,67,M,182,Right,0,59,67,71,56,70,70,,,,,,NaN
9723,Camel Meriem,71,M,174,Right,0,58,65,69,75,45,62,,,,,,NaN
9751,G치bor Babos,71,GK,196,Right,1,,,,,,,70,70,60,70,29,75.0
9771,Orlando Engelaar,73,M,196,Left,1,38,71,71,65,75,61,,,,,,NaN
9799,Pierre-Alain Frau,73,A,175,Right,1,79,72,68,71,54,68,,,,,,NaN
9801,Danijel Ljuboja,73,A,189,Left,1,62,73,64,74,56,68,,,,,,NaN
9805,Craig Bellamy,79,A,175,Right,0,80,78,67,81,62,71,,,,,,NaN
9807,Michel Breuer,68,D,183,Right,0,61,40,56,51,70,74,,,,,,NaN
9815,Gill Swerts,65,D,179,Right,0,65,48,63,65,67,69,,,,,,NaN
9913,Mehdi Nafti,69,M,179,Right,0,55,56,64,65,69,60,,,,,,NaN

In [24]:
fifa_dataset["rating"].mode()

KeyError: 'rating'

,name,rating,position,height,foot,rare,pace,shooting,passing,dribbling,defending,heading,diving,handling,kicking,reflexes,speed,positioning
id,,,,,,,,,,,,,,,,,,
9722,Nicolai Stokholm,67,M,182,Right,0,59,67,71,56,70,70,,,,,,NaN
9723,Camel Meriem,71,M,174,Right,0,58,65,69,75,45,62,,,,,,NaN
9751,G치bor Babos,71,GK,196,Right,1,,,,,,,70,70,60,70,29,75.0
9771,Orlando Engelaar,73,M,196,Left,1,38,71,71,65,75,61,,,,,,NaN
9799,Pierre-Alain Frau,73,A,175,Right,1,79,72,68,71,54,68,,,,,,NaN
9801,Danijel Ljuboja,73,A,189,Left,1,62,73,64,74,56,68,,,,,,NaN
9805,Craig Bellamy,79,A,175,Right,0,80,78,67,81,62,71,,,,,,NaN
9807,Michel Breuer,68,D,183,Right,0,61,40,56,51,70,74,,,,,,NaN
9815,Gill Swerts,65,D,179,Right,0,65,48,63,65,67,69,,,,,,NaN
9913,Mehdi Nafti,69,M,179,Right,0,55,56,64,65,69,60,,,,,,NaN